### ISSUE TITLE
RegistryDateDeserializer is not thread-safe

### ISSUE THREAD

**Issue by jbaudisc** [Apicurio/apicurio-common-rest-client#123]
io.apicurio.rest.client.handler.RegistryDateDeserializer uses SimpleDateFormat, which is not thread-safe, see

https://www.callicoder.com/java-simpledateformat-thread-safety-issues/

In a load test (200 requests/sec.), we encountered in ca. 0,1 % of the requests the following error:

````
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.lang.Long.parseLong(Long.java:721)
	at java.lang.Long.parseLong(Long.java:836)
	at java.text.DigitList.getLong(DigitList.java:195)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2197)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1937)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1545)
	at java.text.DateFormat.parse(DateFormat.java:397)
	at i.a.r.c.h.RegistryDateDeserializer.deserialize(RegistryDateDeserializer.java:54)
	at i.a.r.c.h.RegistryDateDeserializer.deserialize(RegistryDateDeserializer.java:36)
	at c.f.j.d.d.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at c.f.j.d.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at c.f.j.d.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at c.f.j.d.d.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at c.f.j.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at c.f.j.databind.ObjectMapper.readValue(ObjectMapper.java:3722)
	at i.a.r.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:64)
	at i.a.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:204)
	at i.a.r.r.c.i.RegistryClientImpl.getArtifactMetaData(RegistryClientImpl.java:95)
	at i.a.r.r.DefaultSchemaResolver.resolveByCoordinates(DefaultSchemaResolver.java:306)
	at i.a.r.r.DefaultSchemaResolver.lambda$resolveSchemaByArtifactReferenceCached$6(DefaultSchemaResolver.java:297)
	at i.a.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:142)
	at i.a.registry.resolver.ERCache.retry(ERCache.java:181)
	at i.a.registry.resolver.ERCache.getValue(ERCache.java:141)
	at i.a.registry.resolver.ERCache.getByArtifactCoordinates(ERCache.java:131)
	at i.a.r.r.DefaultSchemaResolver.resolveSchemaByArtifactReferenceCached(DefaultSchemaResolver.java:297)
	at i.a.r.r.DefaultSchemaResolver.resolveSchemaByCoordinates(DefaultSchemaResolver.java:175)
	at i.a.r.r.DefaultSchemaResolver.getSchemaFromRegistry(DefaultSchemaResolver.java:120)
	at i.a.r.r.DefaultSchemaResolver.resolveSchema(DefaultSchemaResolver.java:88)
	at i.a.r.s.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:83)
	at i.a.r.s.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:70)
	at n.s.k.p.c.o.s.a.AvroOrderEventSerializer.serialize(AvroOrderEventSerializer.java:34)
	... 82 frames truncated
````

when patching the `RegistryDateDeserializer` to access `SimpleDateFormat` in a `ThreadLocal` variable, like suggested in https://www.javacodegeeks.com/2010/07/java-best-practices-dateformat-in.html, we got no errors

````
public class RegistryDateDeserializer extends JsonDeserializer<Date> {

    /**
     * thread-safe DateFormat, see https://www.javacodegeeks.com/2010/07/java-best-practices-dateformat-in.html
     */
    private ThreadLocal<DateFormat> dateFormat = new ThreadLocal<>() {

        @Override
        public DateFormat get() {
            return super.get();
        }

        @Override
        protected DateFormat initialValue() {
            return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        }

        @Override
        public void remove() {
            super.remove();
        }

        @Override
        public void set(DateFormat value) {
            super.set(value);
        }

    };

    /**
     * @see JsonDeserializer#deserialize(JsonParser, DeserializationContext)
     */
    @Override
    public Date deserialize(JsonParser parser, DeserializationContext context) throws IOException, JacksonException {
        JsonNode node = parser.getCodec().readTree(parser);
        String date = node.textValue();
        
        // Handle zulu timezone and convert to RFC 822.
        if (date != null && date.endsWith("Z")) {
            date = date.replace("Z", "+0000");
        }

        try {
            return dateFormat.get().parse(date);
        } catch (ParseException e) {
        }
        throw new JsonParseException(parser, "Failed to parse date (not a supported format).");
    }
}
````

**Comment by jbaudisc** [comment]
create Pull Request https://github.com/Apicurio/apicurio-common-rest-client/pull/124

**Comment by carlesarnal** [comment]
Thank you very much for raising this. I have merged the PR and will release a new version of the library.
